import React from  'react';

function Articles(props) {

    const articles =  [
        {
          id: 0,
          name:'Will the Buddha Save Him? – A Zen Story',
          image: 'https://images.sadhguru.org/sites/default/files/media_files/sadhguru-wisdom-article-will-buddha-save-him_0.jpg', 
          description: 
          'Man cannot come to it through any organization, through any creed, through any dogma, priest or ritual, not through any philosophical knowledge or psychological technique. He has to find it through the mirror of relationship, through the understanding of the contents of his own mind, through observation and not through intellectual analysis or introspective dissection.Man has built in himself images as a fence of security—religious, political, personal. These manifest as symbols, ideas, beliefs. The burden of these images dominates man’s thinking, his relationships, and his daily life. These images are the causes of our problems for they divide man from man. His perception of life is shaped by the concepts already established in his mind. The content of his consciousness is his entire existence. The individuality is the name, the form and superficial culture he acquires from tradition and environment. The uniqueness of man does not lie in the superficial but in complete freedom from the content of his consciousness, which is common to all humanity. So he is not an individual. Freedom is not a reaction; freedom is not choice. It is man’s pretence that because he has choice he is free. Freedom is pure observation without direction, without fear of punishment and reward. Freedom is without motive; freedom is not at the end of the evolution of man but lies in the first step of his existence. In observation one begins to discover the lack of freedom. Freedom is found in the choiceless awareness of our daily existence and activity.Thought is time. Thought is born of experience and knowledge, which are inseparable from time and the past. Time is the psychological enemy of man. Our action is based on knowledge and therefore time, so man is always a slave to the past. Thought is ever limited and so we live in constant conflict and struggle. There is no psychological evolution. When man becomes aware of the movement of his own thoughts, he will see the division between the thinker and thought, the observer and the observed, the experiencer and the experience. He will discover that this division is an illusion. Then only is there pure observation which is insight without any shadow of the past or of time. This timeless insight brings about a deep, radical mutation in the mind. Total negation is the essence of the positive. When there is negation of all those things that thought has brought about psychologically, only then is there love, which is compassion and intelligence.'
         },
       
         {
            id: 1,
            name:'Will the Buddha Save Him? – A Zen Story',
            image: 'https://images.sadhguru.org/sites/default/files/media_files/sadhguru-wisdom-article-will-buddha-save-him_0.jpg', 
            description: 
            'Man cannot come to it through any organization, through any creed, through any dogma, priest or ritual, not through any philosophical knowledge or psychological technique. He has to find it through the mirror of relationship, through the understanding of the contents of his own mind, through observation and not through intellectual analysis or introspective dissection.Man has built in himself images as a fence of security—religious, political, personal. These manifest as symbols, ideas, beliefs. The burden of these images dominates man’s thinking, his relationships, and his daily life. These images are the causes of our problems for they divide man from man. His perception of life is shaped by the concepts already established in his mind. The content of his consciousness is his entire existence. The individuality is the name, the form and superficial culture he acquires from tradition and environment. The uniqueness of man does not lie in the superficial but in complete freedom from the content of his consciousness, which is common to all humanity. So he is not an individual. Freedom is not a reaction; freedom is not choice. It is man’s pretence that because he has choice he is free. Freedom is pure observation without direction, without fear of punishment and reward. Freedom is without motive; freedom is not at the end of the evolution of man but lies in the first step of his existence. In observation one begins to discover the lack of freedom. Freedom is found in the choiceless awareness of our daily existence and activity.Thought is time. Thought is born of experience and knowledge, which are inseparable from time and the past. Time is the psychological enemy of man. Our action is based on knowledge and therefore time, so man is always a slave to the past. Thought is ever limited and so we live in constant conflict and struggle. There is no psychological evolution. When man becomes aware of the movement of his own thoughts, he will see the division between the thinker and thought, the observer and the observed, the experiencer and the experience. He will discover that this division is an illusion. Then only is there pure observation which is insight without any shadow of the past or of time. This timeless insight brings about a deep, radical mutation in the mind. Total negation is the essence of the positive. When there is negation of all those things that thought has brought about psychologically, only then is there love, which is compassion and intelligence.'
           },
       
           {
            id: 2,
            name:'Will the Buddha Save Him? – A Zen Story',
            image: 'https://images.sadhguru.org/sites/default/files/media_files/sadhguru-isha-wisdom-article-image-fox-does-being-smart-make-you-dumb.jpg', 
            description: 
            'Man cannot come to it through any organization, through any creed, through any dogma, priest or ritual, not through any philosophical knowledge or psychological technique. He has to find it through the mirror of relationship, through the understanding of the contents of his own mind, through observation and not through intellectual analysis or introspective dissection.Man has built in himself images as a fence of security—religious, political, personal. These manifest as symbols, ideas, beliefs. The burden of these images dominates man’s thinking, his relationships, and his daily life. These images are the causes of our problems for they divide man from man. His perception of life is shaped by the concepts already established in his mind. The content of his consciousness is his entire existence. The individuality is the name, the form and superficial culture he acquires from tradition and environment. The uniqueness of man does not lie in the superficial but in complete freedom from the content of his consciousness, which is common to all humanity. So he is not an individual. Freedom is not a reaction; freedom is not choice. It is man’s pretence that because he has choice he is free. Freedom is pure observation without direction, without fear of punishment and reward. Freedom is without motive; freedom is not at the end of the evolution of man but lies in the first step of his existence. In observation one begins to discover the lack of freedom. Freedom is found in the choiceless awareness of our daily existence and activity.Thought is time. Thought is born of experience and knowledge, which are inseparable from time and the past. Time is the psychological enemy of man. Our action is based on knowledge and therefore time, so man is always a slave to the past. Thought is ever limited and so we live in constant conflict and struggle. There is no psychological evolution. When man becomes aware of the movement of his own thoughts, he will see the division between the thinker and thought, the observer and the observed, the experiencer and the experience. He will discover that this division is an illusion. Then only is there pure observation which is insight without any shadow of the past or of time. This timeless insight brings about a deep, radical mutation in the mind. Total negation is the essence of the positive. When there is negation of all those things that thought has brought about psychologically, only then is there love, which is compassion and intelligence.'
           },
       
           {
            id: 3,
            name:'Will the Buddha Save Him? – A Zen Story',
            image: 'https://images.sadhguru.org/sites/default/files/media_files/sadhguru-isha-wisdom-article-image-watercolor-painting-guy-meditating-flying-yoga-mat-how-do-i-handle-confusion-on-spiritual-path.jpg', 
            description: 
            'Man cannot come to it through any organization, through any creed, through any dogma, priest or ritual, not through any philosophical knowledge or psychological technique. He has to find it through the mirror of relationship, through the understanding of the contents of his own mind, through observation and not through intellectual analysis or introspective dissection.Man has built in himself images as a fence of security—religious, political, personal. These manifest as symbols, ideas, beliefs. The burden of these images dominates man’s thinking, his relationships, and his daily life. These images are the causes of our problems for they divide man from man. His perception of life is shaped by the concepts already established in his mind. The content of his consciousness is his entire existence. The individuality is the name, the form and superficial culture he acquires from tradition and environment. The uniqueness of man does not lie in the superficial but in complete freedom from the content of his consciousness, which is common to all humanity. So he is not an individual. Freedom is not a reaction; freedom is not choice. It is man’s pretence that because he has choice he is free. Freedom is pure observation without direction, without fear of punishment and reward. Freedom is without motive; freedom is not at the end of the evolution of man but lies in the first step of his existence. In observation one begins to discover the lack of freedom. Freedom is found in the choiceless awareness of our daily existence and activity.Thought is time. Thought is born of experience and knowledge, which are inseparable from time and the past. Time is the psychological enemy of man. Our action is based on knowledge and therefore time, so man is always a slave to the past. Thought is ever limited and so we live in constant conflict and struggle. There is no psychological evolution. When man becomes aware of the movement of his own thoughts, he will see the division between the thinker and thought, the observer and the observed, the experiencer and the experience. He will discover that this division is an illusion. Then only is there pure observation which is insight without any shadow of the past or of time. This timeless insight brings about a deep, radical mutation in the mind. Total negation is the essence of the positive. When there is negation of all those things that thought has brought about psychologically, only then is there love, which is compassion and intelligence.'
           },
           {
            id: 4,
            name:'Will the Buddha Save Him? – A Zen Story',
            image: 'https://images.sadhguru.org/sites/default/files/media_files/sadhguru-isha-wisdom-article-image-fox-does-being-smart-make-you-dumb.jpg', 
            description: 
            'Man cannot come to it through any organization, through any creed, through any dogma, priest or ritual, not through any philosophical knowledge or psychological technique. He has to find it through the mirror of relationship, through the understanding of the contents of his own mind, through observation and not through intellectual analysis or introspective dissection.Man has built in himself images as a fence of security—religious, political, personal. These manifest as symbols, ideas, beliefs. The burden of these images dominates man’s thinking, his relationships, and his daily life. These images are the causes of our problems for they divide man from man. His perception of life is shaped by the concepts already established in his mind. The content of his consciousness is his entire existence. The individuality is the name, the form and superficial culture he acquires from tradition and environment. The uniqueness of man does not lie in the superficial but in complete freedom from the content of his consciousness, which is common to all humanity. So he is not an individual. Freedom is not a reaction; freedom is not choice. It is man’s pretence that because he has choice he is free. Freedom is pure observation without direction, without fear of punishment and reward. Freedom is without motive; freedom is not at the end of the evolution of man but lies in the first step of his existence. In observation one begins to discover the lack of freedom. Freedom is found in the choiceless awareness of our daily existence and activity.Thought is time. Thought is born of experience and knowledge, which are inseparable from time and the past. Time is the psychological enemy of man. Our action is based on knowledge and therefore time, so man is always a slave to the past. Thought is ever limited and so we live in constant conflict and struggle. There is no psychological evolution. When man becomes aware of the movement of his own thoughts, he will see the division between the thinker and thought, the observer and the observed, the experiencer and the experience. He will discover that this division is an illusion. Then only is there pure observation which is insight without any shadow of the past or of time. This timeless insight brings about a deep, radical mutation in the mind. Total negation is the essence of the positive. When there is negation of all those things that thought has brought about psychologically, only then is there love, which is compassion and intelligence.'
           },
       
           {
            id: 5,
            name:'Will the Buddha Save Him? – A Zen Story',
            image: 'https://images.sadhguru.org/sites/default/files/media_files/sadhguru-isha-wisdom-article-image-watercolor-painting-guy-meditating-flying-yoga-mat-how-do-i-handle-confusion-on-spiritual-path.jpg', 
            description: 
            'Man cannot come to it through any organization, through any creed, through any dogma, priest or ritual, not through any philosophical knowledge or psychological technique. He has to find it through the mirror of relationship, through the understanding of the contents of his own mind, through observation and not through intellectual analysis or introspective dissection.Man has built in himself images as a fence of security—religious, political, personal. These manifest as symbols, ideas, beliefs. The burden of these images dominates man’s thinking, his relationships, and his daily life. These images are the causes of our problems for they divide man from man. His perception of life is shaped by the concepts already established in his mind. The content of his consciousness is his entire existence. The individuality is the name, the form and superficial culture he acquires from tradition and environment. The uniqueness of man does not lie in the superficial but in complete freedom from the content of his consciousness, which is common to all humanity. So he is not an individual. Freedom is not a reaction; freedom is not choice. It is man’s pretence that because he has choice he is free. Freedom is pure observation without direction, without fear of punishment and reward. Freedom is without motive; freedom is not at the end of the evolution of man but lies in the first step of his existence. In observation one begins to discover the lack of freedom. Freedom is found in the choiceless awareness of our daily existence and activity.Thought is time. Thought is born of experience and knowledge, which are inseparable from time and the past. Time is the psychological enemy of man. Our action is based on knowledge and therefore time, so man is always a slave to the past. Thought is ever limited and so we live in constant conflict and struggle. There is no psychological evolution. When man becomes aware of the movement of his own thoughts, he will see the division between the thinker and thought, the observer and the observed, the experiencer and the experience. He will discover that this division is an illusion. Then only is there pure observation which is insight without any shadow of the past or of time. This timeless insight brings about a deep, radical mutation in the mind. Total negation is the essence of the positive. When there is negation of all those things that thought has brought about psychologically, only then is there love, which is compassion and intelligence.'
           },
           {
            id: 6,
            name:'Will the Buddha Save Him? – A Zen Story',
            image: 'https://images.sadhguru.org/sites/default/files/media_files/sadhguru-isha-wisdom-article-image-fox-does-being-smart-make-you-dumb.jpg', 
            description: 
            'Man cannot come to it through any organization, through any creed, through any dogma, priest or ritual, not through any philosophical knowledge or psychological technique. He has to find it through the mirror of relationship, through the understanding of the contents of his own mind, through observation and not through intellectual analysis or introspective dissection.Man has built in himself images as a fence of security—religious, political, personal. These manifest as symbols, ideas, beliefs. The burden of these images dominates man’s thinking, his relationships, and his daily life. These images are the causes of our problems for they divide man from man. His perception of life is shaped by the concepts already established in his mind. The content of his consciousness is his entire existence. The individuality is the name, the form and superficial culture he acquires from tradition and environment. The uniqueness of man does not lie in the superficial but in complete freedom from the content of his consciousness, which is common to all humanity. So he is not an individual. Freedom is not a reaction; freedom is not choice. It is man’s pretence that because he has choice he is free. Freedom is pure observation without direction, without fear of punishment and reward. Freedom is without motive; freedom is not at the end of the evolution of man but lies in the first step of his existence. In observation one begins to discover the lack of freedom. Freedom is found in the choiceless awareness of our daily existence and activity.Thought is time. Thought is born of experience and knowledge, which are inseparable from time and the past. Time is the psychological enemy of man. Our action is based on knowledge and therefore time, so man is always a slave to the past. Thought is ever limited and so we live in constant conflict and struggle. There is no psychological evolution. When man becomes aware of the movement of his own thoughts, he will see the division between the thinker and thought, the observer and the observed, the experiencer and the experience. He will discover that this division is an illusion. Then only is there pure observation which is insight without any shadow of the past or of time. This timeless insight brings about a deep, radical mutation in the mind. Total negation is the essence of the positive. When there is negation of all those things that thought has brought about psychologically, only then is there love, which is compassion and intelligence.'
           },
       
           {
            id: 7,
            name:'Will the Buddha Save Him? – A Zen Story',
            image: 'https://images.sadhguru.org/sites/default/files/media_files/sadhguru-isha-wisdom-article-image-watercolor-painting-guy-meditating-flying-yoga-mat-how-do-i-handle-confusion-on-spiritual-path.jpg', 
            description: 
            'Man cannot come to it through any organization, through any creed, through any dogma, priest or ritual, not through any philosophical knowledge or psychological technique. He has to find it through the mirror of relationship, through the understanding of the contents of his own mind, through observation and not through intellectual analysis or introspective dissection.Man has built in himself images as a fence of security—religious, political, personal. These manifest as symbols, ideas, beliefs. The burden of these images dominates man’s thinking, his relationships, and his daily life. These images are the causes of our problems for they divide man from man. His perception of life is shaped by the concepts already established in his mind. The content of his consciousness is his entire existence. The individuality is the name, the form and superficial culture he acquires from tradition and environment. The uniqueness of man does not lie in the superficial but in complete freedom from the content of his consciousness, which is common to all humanity. So he is not an individual. Freedom is not a reaction; freedom is not choice. It is man’s pretence that because he has choice he is free. Freedom is pure observation without direction, without fear of punishment and reward. Freedom is without motive; freedom is not at the end of the evolution of man but lies in the first step of his existence. In observation one begins to discover the lack of freedom. Freedom is found in the choiceless awareness of our daily existence and activity.Thought is time. Thought is born of experience and knowledge, which are inseparable from time and the past. Time is the psychological enemy of man. Our action is based on knowledge and therefore time, so man is always a slave to the past. Thought is ever limited and so we live in constant conflict and struggle. There is no psychological evolution. When man becomes aware of the movement of his own thoughts, he will see the division between the thinker and thought, the observer and the observed, the experiencer and the experience. He will discover that this division is an illusion. Then only is there pure observation which is insight without any shadow of the past or of time. This timeless insight brings about a deep, radical mutation in the mind. Total negation is the essence of the positive. When there is negation of all those things that thought has brought about psychologically, only then is there love, which is compassion and intelligence.'
           },
           {
            id: 8,
            name:'Will the Buddha Save Him? – A Zen Story',
            image: 'https://images.sadhguru.org/sites/default/files/media_files/sadhguru-isha-wisdom-article-image-fox-does-being-smart-make-you-dumb.jpg', 
            description: 
            'Man cannot come to it through any organization, through any creed, through any dogma, priest or ritual, not through any philosophical knowledge or psychological technique. He has to find it through the mirror of relationship, through the understanding of the contents of his own mind, through observation and not through intellectual analysis or introspective dissection.Man has built in himself images as a fence of security—religious, political, personal. These manifest as symbols, ideas, beliefs. The burden of these images dominates man’s thinking, his relationships, and his daily life. These images are the causes of our problems for they divide man from man. His perception of life is shaped by the concepts already established in his mind. The content of his consciousness is his entire existence. The individuality is the name, the form and superficial culture he acquires from tradition and environment. The uniqueness of man does not lie in the superficial but in complete freedom from the content of his consciousness, which is common to all humanity. So he is not an individual. Freedom is not a reaction; freedom is not choice. It is man’s pretence that because he has choice he is free. Freedom is pure observation without direction, without fear of punishment and reward. Freedom is without motive; freedom is not at the end of the evolution of man but lies in the first step of his existence. In observation one begins to discover the lack of freedom. Freedom is found in the choiceless awareness of our daily existence and activity.Thought is time. Thought is born of experience and knowledge, which are inseparable from time and the past. Time is the psychological enemy of man. Our action is based on knowledge and therefore time, so man is always a slave to the past. Thought is ever limited and so we live in constant conflict and struggle. There is no psychological evolution. When man becomes aware of the movement of his own thoughts, he will see the division between the thinker and thought, the observer and the observed, the experiencer and the experience. He will discover that this division is an illusion. Then only is there pure observation which is insight without any shadow of the past or of time. This timeless insight brings about a deep, radical mutation in the mind. Total negation is the essence of the positive. When there is negation of all those things that thought has brought about psychologically, only then is there love, which is compassion and intelligence.'
           }
      ]

      const articleList = articles.map( article => <h2>{article.name}</h2>)

    return(
        <div>{articleList}</div>
    );

}

export default Articles;